const CONSTANTS = {
  BOARD_WIDTH: 800,
  BOARD_HEIGHT: 500,

  PADDLE_WIDTH: 12,
  PADDLE_HEIGHT: 90,
  PADDLE_MARGIN: 20,
  PADDLE_SPEED: 6,

  BALL_RADIUS: 8,
  BALL_SPEED: 5,
  BALL_SPEED_INCREMENT: 0.3,
  BALL_MAX_SPEED: 14,

  MAX_SCORE: 5,

  TICK_RATE: 60,
};

module.exports = CONSTANTS;
